title: mike blog
subtitle: blog
description: yah
author: mike
email: 
lang: en
baseurl: ""
url: ""
permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
kramdown:
  input: GFM
timezone: Etc/UTC
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: mike
  - scope:
      path: ""
    values:
      layout: default
      body_class: ""

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor
